### ISSUE TITLE
Not working anymore on newer Bulma versions

### ISSUE THREAD

**Issue by tyu1996** [postare/bulma-modal-fx#16]
The modal effects other than "normal" will no longer working on newer versions of Bulma. This has to do with the new naming of modal classes.

To reproduce this, simply throw in the modal-fx class:
```html
<div id="modal-id" class="modal modal-fx-slideBottom">
    <div class="modal-background"></div>
    <div class="modal-card">
        <!-- Any other Bulma elements you want -->
    </div>
    <button class="modal-close is-large" aria-label="close"></button>
</div>
```

Solution, change from here(original):
```css
.modal.modal-fx-slideBottom .modal-content {
        -webkit-transform: translateY(20%);
        -o-transform: translateY(20%);
        transform: translateY(20%);
        opacity: 0;
        -webkit-transition: all .3s;
        -o-transition: all .3s;
        transition: all .3s
    }

    .modal.modal-fx-slideBottom.is-active .modal-content {
        -webkit-transform: translateY(0);
        -o-transform: translateY(0);
        transform: translateY(0);
        opacity: 1
    }
```
...to this...
```css
.modal.modal-fx-slideBottom .modal-card {
        -webkit-transform: translateY(20%);
        -o-transform: translateY(20%);
        transform: translateY(20%);
        opacity: 0;
        -webkit-transition: all .3s;
        -o-transition: all .3s;
        transition: all .3s
    }

    .modal.modal-fx-slideBottom.is-active .modal-card {
        -webkit-transform: translateY(0);
        -o-transform: translateY(0);
        transform: translateY(0);
        opacity: 1
    }
```

Bulma has changed the name of `modal-content` to `modal-card`. Hence, updating the target class name `modal-content` to `modal-card` makes it work again!
